--- #YAML:1.0
name:                Getopt-Long-Descriptive
version:             0.074
abstract:            Getopt::Long with usage text
license:             ~
author:              
    - Hans Dieter Pearcey <hdp@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    IO::Scalar:                    0
    List::Util:                    0
    Params::Validate:              0.74
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
