# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Getopt-Long-Descriptive
version:      0.073
version_from: lib/Getopt/Long/Descriptive.pm
installdirs:  site
requires:
    IO::Scalar:                    0
    List::Util:                    0
    Params::Validate:              0.74
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
