--- #YAML:1.0
name:               Getopt-Long-Descriptive
version:            0.087
abstract:           Getopt::Long, but simpler and more powerful
author:
    - Hans Dieter Pearcey <hdp@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:      2.33
    List::Util:        0
    Params::Validate:  0.74
    Sub::Exporter:     0.972
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
